-- Noise & stealth (§8).
--
-- Noise is generated by ACTIONS, not equipment: running, jumping, digging,
-- placing, fighting, killing. Quiet is a whole playstyle — walking keeps
-- you hidden but slow; working fast draws attention.
--
-- Noise MULTIPLIES with group size (§8 confirmed): sound from players near
-- each other scales in volume and travel distance. This is the primary
-- solo advantage: groups gain power and lose concealment.
--
-- Consumers: creatures. A noise event provokes hostiles within its radius
-- and gives them the position to investigate — the "something is in the
-- next room" tension comes from here, not a dedicated mechanic.

scavock_noise = {}

local LEVELS = {
	walk = 8,
	sprint = 24,
	crouch = 3,
	dig = 15,
	place = 10,
	hit = 20,
	kill = 28,
	explosion = 60,
}
scavock_noise.LEVELS = LEVELS

-- §8: sound scales with the number of sources — nearby players multiply
-- both volume and travel distance
local function group_multiplier(pos)
	local n = 0
	for _, player in ipairs(core.get_connected_players()) do
		if vector.distance(player:get_pos(), pos) < 10 then
			n = n + 1
		end
	end
	return 1 + 0.5 * math.max(0, n - 1)
end

-- Emit a noise: provokes creatures in radius and points them at it.
function scavock.noise(pos, level, source_name)
	local radius = (LEVELS[level] or level or 8) * group_multiplier(pos)
	for obj in core.objects_inside_radius(pos, radius) do
		local ent = obj:get_luaentity()
		if ent and ent._scavock_creature and ent._hears then
			ent:_hears(pos, radius, source_name)
		end
	end
	return radius
end

-- ---------------------------------------------------------------------------
-- Emitters
-- ---------------------------------------------------------------------------

-- footsteps: cadence depends on movement mode
local step_t = {}
core.register_globalstep(function(dtime)
	for _, player in ipairs(core.get_connected_players()) do
		local name = player:get_player_name()
		step_t[name] = (step_t[name] or 0) + dtime
		if step_t[name] >= 0.8 then
			step_t[name] = 0
			local ctrl = player:get_player_control()
			local moving = ctrl.up or ctrl.down or ctrl.left or ctrl.right
			if moving and not scavock.downed[name] then
				local level = "walk"
				if ctrl.aux1 and ctrl.up then
					level = "sprint"      -- §7: sprinting is loud; fleeing broadcasts
				elseif ctrl.sneak then
					level = "crouch"
				end
				scavock.noise(player:get_pos(), level, name)
			end
		end
	end
end)

core.register_on_dignode(function(pos, oldnode, digger)
	if digger and digger:is_player() then
		scavock.noise(pos, "dig", digger:get_player_name())
	end
end)
core.register_on_placenode(function(pos, newnode, placer)
	if placer and placer:is_player() then
		scavock.noise(pos, "place", placer:get_player_name())
	end
end)
core.register_on_punchplayer(function(player, hitter)
	scavock.noise(player:get_pos(), "hit",
		hitter and hitter:is_player() and hitter:get_player_name() or nil)
end)
core.register_on_dieplayer(function(player)
	scavock.noise(player:get_pos(), "kill", nil)
end)

core.register_on_leaveplayer(function(player)
	step_t[player:get_player_name()] = nil
end)
